name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: {} # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3

    - name: Sync upstream changes
      uses: aormsby/Fork-Sync-With-Upstream-action@v3
      with:
        target_sync_branch: develop
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: elizaOS/eliza
        upstream_sync_branch: develop
